/* soapServer.cpp
   Generated by gSOAP 2.8.17r from beopfunctions.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.cpp ver 2.8.17r 2014-06-23 09:53:44 GMT")


extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "beop-getvalue"))
		return soap_serve_beop_getvalue(soap);
	if (!soap_match_tag(soap, soap->tag, "beop-getvalue-multiple"))
		return soap_serve_beop_getvalue_multiple(soap);
	if (!soap_match_tag(soap, soap->tag, "beop-userlogin"))
		return soap_serve_beop_userlogin(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_beop_getvalue(struct soap *soap)
{	struct beop_getvalue soap_tmp_beop_getvalue;
	struct beop_getvalueResponse soap_tmp_beop_getvalueResponse;
	std::wstring soap_tmp_beop__string;
	soap_default_beop_getvalueResponse(soap, &soap_tmp_beop_getvalueResponse);
	soap_default_beop__string(soap, &soap_tmp_beop__string);
	soap_tmp_beop_getvalueResponse.strPointValue = &soap_tmp_beop__string;
	soap_default_beop_getvalue(soap, &soap_tmp_beop_getvalue);
	if (!soap_get_beop_getvalue(soap, &soap_tmp_beop_getvalue, "beop-getvalue", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = beop_getvalue(soap, soap_tmp_beop_getvalue.strPointName, soap_tmp_beop_getvalueResponse.strPointValue);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_beop_getvalueResponse(soap, &soap_tmp_beop_getvalueResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_beop_getvalueResponse(soap, &soap_tmp_beop_getvalueResponse, "beop-getvalueResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_beop_getvalueResponse(soap, &soap_tmp_beop_getvalueResponse, "beop-getvalueResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_beop_getvalue_multiple(struct soap *soap)
{	struct beop_getvalue_multiple soap_tmp_beop_getvalue_multiple;
	struct beop_getvalue_multipleResponse soap_tmp_beop_getvalue_multipleResponse;
	std::wstring soap_tmp_beop__string;
	soap_default_beop_getvalue_multipleResponse(soap, &soap_tmp_beop_getvalue_multipleResponse);
	soap_default_beop__string(soap, &soap_tmp_beop__string);
	soap_tmp_beop_getvalue_multipleResponse.strPointValueList = &soap_tmp_beop__string;
	soap_default_beop_getvalue_multiple(soap, &soap_tmp_beop_getvalue_multiple);
	if (!soap_get_beop_getvalue_multiple(soap, &soap_tmp_beop_getvalue_multiple, "beop-getvalue-multiple", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = beop_getvalue_multiple(soap, soap_tmp_beop_getvalue_multiple.strPointNameList, soap_tmp_beop_getvalue_multipleResponse.strPointValueList);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_beop_getvalue_multipleResponse(soap, &soap_tmp_beop_getvalue_multipleResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_beop_getvalue_multipleResponse(soap, &soap_tmp_beop_getvalue_multipleResponse, "beop-getvalue-multipleResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_beop_getvalue_multipleResponse(soap, &soap_tmp_beop_getvalue_multipleResponse, "beop-getvalue-multipleResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_beop_userlogin(struct soap *soap)
{	struct beop_userlogin soap_tmp_beop_userlogin;
	struct beop_userloginResponse soap_tmp_beop_userloginResponse;
	std::wstring soap_tmp_beop__string;
	soap_default_beop_userloginResponse(soap, &soap_tmp_beop_userloginResponse);
	soap_default_beop__string(soap, &soap_tmp_beop__string);
	soap_tmp_beop_userloginResponse.userInfo = &soap_tmp_beop__string;
	soap_default_beop_userlogin(soap, &soap_tmp_beop_userlogin);
	if (!soap_get_beop_userlogin(soap, &soap_tmp_beop_userlogin, "beop-userlogin", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = beop_userlogin(soap, soap_tmp_beop_userlogin.userName, soap_tmp_beop_userlogin.userPwd, soap_tmp_beop_userloginResponse.userInfo);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_beop_userloginResponse(soap, &soap_tmp_beop_userloginResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_beop_userloginResponse(soap, &soap_tmp_beop_userloginResponse, "beop-userloginResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_beop_userloginResponse(soap, &soap_tmp_beop_userloginResponse, "beop-userloginResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.cpp */
